apiVersion: v1
kind: Service
metadata:
  name: word-sql-db
  labels:
    {{- include "helm-sql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    {{- include "helm-sql.selectorLabels" . | nindent 4 }}
