apiVersion: v1
kind: Service
metadata:
  name: {{ include "hwordpress.fullname" . }}
  labels:
    {{- include "hwordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30598
      protocol: TCP
      name: http
  selector:
    {{- include "hwordpress.selectorLabels" . | nindent 4 }}
